# Site Settings
title: Start Jekyll
email: email@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: '/ecopetpalace'
url: 'https://jeffrey-over.github.io/ecopetpalace'
twitter_username: taniarascia
github_username: taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM